### PR TITLE
Update npm scripts and gemfile to run the repository in all systems

### PR DESCRIPTION
**Pull request by MustafaSalih**

### CODE REVIEW

**Comment by nilswindisch** [comment]
seems to work fine, great work.

One thing though: if run locally, the in-page URLs point to metrics-project.net which makes it impossible to navigate (locally) via in-page links. Maybe you can add a switch, that locally run systems use localhost?!

**Comment by MustafaSalih** [comment]
**Concerning the in-page URLs**
As I can see here (https://stackoverflow.com/a/37087102/3256613) the best solution is to have two config files. Then we can use different command to run Jekyll in order to avoid errors.

**Comment by nilswindisch** [comment]
I've updated package.json to support local URLs, please test on your system and report back.

**Comment by MustafaSalih** [comment]
It works on mac fine, but I needed to call `npm run build:jekyll` skript additionally again on windows to support local URLs. Afterwards it also works fine on windows!

**Pull request merged**
